Commit dist package
because rollup can't resolve the cyclic dependencies and importing the library would result in:
```
var prototype$K = (HeadlessView.prototype = new View_1());
                                            ^
TypeError: View_1 is not a constructor
    at Object.<anonymous> (/Users/lukasgeiger/code/vega-embed-all/dist/index.cjs.js:17451:45)
```